name: Deploy Tagged Version

on:
  push:
    tags:
      - 'v*.*.*'  # This will match tags like v1.0.0, v2.1.3, etc.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from tag
        run: |
          # Remove the 'v' prefix from the tag
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 179.27.96.162
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ProyGrad2024
            git fetch --all --tags --force
            git checkout v${{ env.APP_VERSION }}
            docker-compose down
            export APP_VERSION=${{ env.APP_VERSION }} && ENVIRONMENT=prod docker-compose up --build -d 